### ISSUE TITLE
akhq: generate docker-compose file

### ISSUE THREAD

**Issue by pascalgrimaud** [fdelbrayelle/generator-jhipster-kafka#15]
See https://akhq.io/
A new docker-compose file `akhq.yml` should be generated in `src/main/docker`

It will help the developper to code their application with Kafka

**Comment by fdelbrayelle** [comment]
Do you mean to add an `akhq` service like this just like [here](https://raw.githubusercontent.com/tchiotludo/akhq/master/docker-compose.yml)?

```
  akhq:
    # build:
    #   context: .
    image: tchiotludo/akhq
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: "kafka:9092"
              schema-registry:
                url: "http://schema-registry:8085"
              connect:
                url: "http://connect:8083"
    ports:
      - 8080:8080
    links:
      - kafka
      - schema-registry
```
