### ISSUE TITLE
Consumer configuration lost

### ISSUE THREAD

**Issue by monxxi** [fdelbrayelle/generator-jhipster-kafka#41]
##### **Overview of the issue**
when i use the module to generate Producer & Consumer, it works fine, but when in a step 2 i want to generate only producers for example, all properties are removed from application.yml and the final application doesn't work anymore . 

here the message from the terminal.
```bash
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jhiOrderConsumer' defined in file [/home/monxxi/app/kafka/kafka-test-newGeneration/target/classes/test/kafka/msng/service/kafka/consumer/JhiOrderConsumer.class]: Unexpected exception during bean creation; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'kafka.consumer.jhiOrder.name' in value "${kafka.consumer.jhiOrder.name}"
```

First step : when i chose producer&consumer, the application.yml part generated is this one.
```yaml
kafka:
  '[bootstrap.servers]': localhost:9092
  consumer:
    jhiOrder:
      name: jhi-order-topic
      enabled: true
      '[key.deserializer]': org.apache.kafka.common.serialization.StringDeserializer
      '[value.deserializer]': test.kafka.msng.service.kafka.deserializer.JhiOrderDeserializer
      '[group.id]': jhipkafn-g
      '[auto.offset.reset]': earliest
    jhiProduct:
      name: jhi-product-topic
      enabled: true
      '[key.deserializer]': org.apache.kafka.common.serialization.StringDeserializer
      '[value.deserializer]': test.kafka.msng.service.kafka.deserializer.JhiProductDeserializer
      '[group.id]': jhipkafn-g
      '[auto.offset.reset]': earliest
  producer:
    jhiOrder:
      name: jhi-order-topic
      enabled: true
      '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
      '[value.serializer]': test.kafka.msng.service.kafka.serializer.JhiOrderSerializer
    jhiProduct:
      name: jhi-product-topic
      enabled: true
      '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
      '[value.serializer]': test.kafka.msng.service.kafka.serializer.JhiProductSerializer
```

and after using the module with only producer chosen, here the application.yml part newly generated. 

```yaml
kafka:
  '[bootstrap.servers]': localhost:9092
  
  producer:
    jhiOrder:
      name: jhi-order-topic
      enabled: true
      '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
      '[value.serializer]': test.kafka.msng.service.kafka.serializer.JhiOrderSerializer
    jhiProduct:
      name: jhi-product-topic
      enabled: true
      '[key.serializer]': org.apache.kafka.common.serialization.StringSerializer
      '[value.serializer]': test.kafka.msng.service.kafka.serializer.JhiProductSerializer
```

##### **Motivation for or Use Case**
it could be interesting to not override the full configuration but keep in memory, the producer & consumer already generated and adapt the final configuration according to the previous generation.

##### **Reproduce the error**
generate an app with the .yo-rc.json

use the module kafka `yo jhipster-kafka` to generate producer and consumer.

after reuse the module kafka  `yo jhipster-kafka` to generate only producer.

##### **JHipster Version(s)**
```
jhipkafn-g@0.0.0 /home/monxxi/app/kafka/kafka-test-newGeneration
└── generator-jhipster@6.8.0 

```

##### **JHipster configuration, a `.yo-rc.json` file generated in the root folder**

<details>
<summary>.yo-rc.json file</summary>
<pre>
{
  "generator-jhipster": {
    "promptValues": {
      "packageName": "test.kafka.msng",
      "nativeLanguage": "fr"
    },
    "jhipsterVersion": "6.8.0",
    "applicationType": "microservice",
    "baseName": "jhipkafnG",
    "packageName": "test.kafka.msng",
    "packageFolder": "test/kafka/msng",
    "serverPort": "8081",
    "authenticationType": "jwt",
    "cacheProvider": "hazelcast",
    "enableHibernateCache": true,
    "websocket": false,
    "databaseType": "sql",
    "devDatabaseType": "h2Disk",
    "prodDatabaseType": "mysql",
    "searchEngine": false,
    "messageBroker": "kafka",
    "serviceDiscoveryType": "eureka",
    "buildTool": "maven",
    "enableSwaggerCodegen": false,
    "jwtSecretKey": "bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl",
    "embeddableLaunchScript": false,
    "creationTimestamp": 1589537055990,
    "testFrameworks": [],
    "jhiPrefix": "jhi",
    "entitySuffix": "",
    "dtoSuffix": "DTO",
    "otherModules": [],
    "enableTranslation": true,
    "clientPackageManager": "npm",
    "nativeLanguage": "fr",
    "languages": ["fr"],
    "blueprints": [],
    "skipClient": true,
    "skipUserManagement": true
  }
}

</pre>
</details>

##### **JDL for the Entity configuration(s) `entityName.json` files generated in the `.jhipster` directory**

<details>
<summary>JDL entity definitions</summary>

<pre>
entity JhiOrder {
  code Integer,
  name String
}
entity JhiProduct {
  name String,
  price BigDecimal
}
relationship ManyToMany {
  JhiProduct{jhiOrder} to JhiOrder{jhiProduct}
}

dto JhiOrder, JhiProduct with mapstruct
service JhiOrder, JhiProduct with serviceImpl
microservice JhiOrder, JhiProduct with jhipkafnG
clientRootFolder JhiOrder, JhiProduct with jhipkafnG

</pre>
</details>

##### **Environment and Tools**

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)

git version 2.20.1

node: v12.16.1

npm: 6.13.4

yeoman: 3.1.1

Docker version 19.03.8, build afacb8b7f0

docker-compose version 1.21.0, build unknown

- [x] Checking this box is mandatory (this is just to show you read everything)
